package com.testmile.setu.agent.core.websvc.guiauto.helpers;

public enum AutomatorActionType {
	GO_TO_URL,
	FIND_ELEMENT,
	FIND_MULTIELEMENT, 
	SWITCH_TO_FRAME,
	
	// Window Actions
	GET_CURRENT_WINDOW_HANDLE,
	GET_WINDOW_TITLE,
	MAXIMIZE_WINDOW,
	GET_CURRENT_WINDOW_SIZE,
	SET_WINDOW_SIZE,
	GET_ALL_WINDOW_HANDLES,
	SWITCH_TO_WINDOW,
	CLOSE_CURRENT_WINDOW, 
	
	EXECUTE_JAVASCRIPT, 
}
