package com.testmile.daksha.core.guiauto.gui;

public enum GuiActionType {
	CREATE_GUI,
	
	CREATE_ELEMENT,
	CREATE_MULTIELEMENT,
	CREATE_DROPDOWN,
	CREATE_RADIOGROUP,
	CREATE_FRAME,
	CREATE_CHILD_WINDOW,
	CREATE_NEW_CHILD_WINDOW,
	CREATE_ALERT,
}
