package setuexp;

public enum DropDownActionType {
	HAS_VISIBLE_TEXT_SELECTED,
	HAS_VALUE_SELECTED,
	HAS_INDEX_SELECTED,
	GET_FIRST_SELECTED_OPTION_TEXT,
	SELECT_BY_VALUE,
	SELECT_BY_VISIBLE_TEXT,
	SELECT_BY_INDEX
}
