package setuexp;

public enum GuiAutomatorActionType {
	LAUNCH, 
	QUIT,
	
	NAVIGATE_BROWSER, 
	
	CREATE_ELEMENT,
	CREATE_MULTIELEMENT,
	CREATE_DROPDOWN,
	CREATE_RADIOGROUP,
	CREATE_FRAME,
	GET_MAIN_WINDOW,
	CREATE_CHILD_WINDOW,
	CREATE_NEW_CHILD_WINDOW,
	
	EXECUTE_JAVASCRIPT,
	HANDLE_ALERT, 

	CLOSE_ALL_CHILD_WINDOWS,
}
