package com.testmile.trishanku.tpi.enums;

public enum ValueType {
	BOOLEAN, STRING, STRING_LIST, NULL, NUMBER, NUMBER_LIST, LIST, ANYREF, ENUM, ENUM_LIST, INTEGER, ANYREF_LIST, FLOAT, DOUBLE, LONG, NOT_SET, NA, INT_LIST
}
