package com.testmile.setu.actor.core.guiauto.translator;


public enum GuiAutomatorActionType {
	QUIT,
	
	GO_TO_URL,
	FIND_MULTIELEMENT, 
	FIND_ELEMENT,
	
	// Window Actions
	GET_CURRENT_WINDOW_HANDLE,
	GET_CURRENT_WINDOW_TITLE,
	MAXIMIZE_CURRENT_WINDOW,
	GET_CURRENT_WINDOW_SIZE,
	SET_CURRENT_WINDOW_SIZE,
	GET_ALL_WINDOW_HANDLES,
	FOCUS_ON_WINDOW,
	CLOSE_CURRENT_WINDOW, 
	
	EXECUTE_JAVASCRIPT, 

	IS_BROWSER_ALERT_PRESENT,
    CONFIRM_BROWSER_ALERT,
    DISMISS_BROWSER_ALERT,
    SEND_TEXT_TO_BROWSER_ALERT,
    GET_TEXT_FROM_BROWSER_ALERT,
    
    GET_CURRENT_MOBILE_VIEW_CONTEXT,
    GET_ALL_MOBILE_VIEW_CONTEXTS,
    FOCUS_ON_MOBILE_VIEW_CONTEXT,
    
    FOCUS_ON_FRAME,
    FOCUS_ON_PARENT_FRAME,
    FOCUS_ON_DOM_ROOT
}
