package com.testmile.setu.requester;

public enum SetuActionType {
	TESTSESSION_INIT,
	TESTSESSION_FINISH,
	
	TESTSESSION_LOAD_PROJECT_CONF,
	TESTSESSION_REGISTER_CONFIG,
	
	TESTSESSION_CREATE_FILE_DATA_SOURCE,
	
	TESTSESSION_LAUNCH_GUIAUTOMATOR,
	TESTSESSION_QUIT_GUIAUTOMATOR,
	
	CONFIGURATOR_GET_SETU_OPTION_VALUE,
	CONFIGURATOR_GET_USER_OPTION_VALUE,
	
	DATASOURCE_GET_NEXT_RECORD,
	DATASOURCE_GET_ALL_RECORDS,
	DATASOURCE_RESET,
	
	/* -----------------------------------
	 * BEGIN Actions for Automator and Gui 
	 * ----------------------------------- */
	
	GUIAUTO_BROWSER_GO_TO_URL,
	GUIAUTO_BROWSER_GO_BACK,
	GUIAUTO_BROWSER_GO_FORWARD,
	GUIAUTO_BROWSER_REFRESH,
	GUIAUTO_BROWSER_EXECUTE_JAVASCRIPT,
	
	GUIAUTO_CREATE_ELEMENT,
	GUIAUTO_CREATE_MULTIELEMENT,
	GUIAUTO_CREATE_DROPDOWN,
	GUIAUTO_CREATE_RADIOGROUP,
	GUIAUTO_CREATE_FRAME,
	GUIAUTO_CREATE_ALERT,
	
	GUIAUTO_CONFIRM_ALERT,
	GUIAUTO_DISMISS_ALERT,
	GUIAUTO_GET_TEXT_FROM_ALERT,
	GUIAUTO_SEND_TEXT_TO_ALERT,

	GUIAUTO_GET_MAIN_WINDOW,
	GUIAUTO_GET_DOM_ROOT,
	
	/* ---
	 * END
	 * --- */
	
	GUIAUTO_GUIMGR_CREATE_GUI,
	GUIAUTO_GUI_CREATE_GUI,
	
	GUIAUTO_ELEMENT_ENTER_TEXT,
	GUIAUTO_ELEMENT_SET_TEXT,
	GUIAUTO_ELEMENT_CLEAR_TEXT,
	
	GUIAUTO_ELEMENT_CLICK, 
	
	GUIAUTO_ELEMENT_WAIT_UNTIL_CLICKABLE, 
	
	GUIAUTO_ELEMENT_CHECK,
	GUIAUTO_ELEMENT_UNCHECK,
	
	// Common to Dropdown and Radiogroup
	GUIAUTO_SELECTABLE_ELEMENTGROUP_HAS_VALUE_SELECTED,
	GUIAUTO_SELECTABLE_ELEMENTGROUP_HAS_INDEX_SELECTED,
	GUIAUTO_SELECTABLE_ELEMENTGROUP_SELECT_BY_VALUE,
	GUIAUTO_SELECTABLE_ELEMENTGROUP_SELECT_BY_INDEX, 
	GUIAUTO_SELECTABLE_ELEMENTGROUP_GET_FIRST_SELECTED_OPTION_VALUE,
	
	GUIAUTO_DROPDOWN_HAS_VISIBLE_TEXT_SELECTED,
	GUIAUTO_DROPDOWN_GET_FIRST_SELECTED_OPTION_TEXT,
	GUIAUTO_DROPDOWN_SELECT_BY_VISIBLE_TEXT,

	GUIAUTO_DOMROOT_FOCUS,
	GUIAUTO_DOMROOT_CREATE_FRAME,
	
	GUIAUTO_FRAME_FOCUS,
	GUIAUTO_FRAME_CREATE_FRAME,
	GUIAUTO_FRAME_GET_PARENT,
	
	GUIAUTO_WINDOW_FOCUS,
	GUIAUTO_WINDOW_GET_TITLE, 
	
	GUIAUTO_MAIN_WINDOW_MAXIMIZE,
	GUIAUTO_MAIN_WINDOW_CREATE_CHILD_WINDOW,
	GUIAUTO_MAIN_WINDOW_GET_NEWLY_LAUNCHED_CHILD_WINDOW,
	GUIAUTO_MAIN_WINDOW_CLOSE_ALL_CHILD_WINDOWS,
	
	GUIAUTO_CHILD_WINDOW_CLOSE,
}
