package daksha.tpi.enums;

public enum DakshaOption {
	ROOT_DIR,
	LOG_DIR,
	TOOLS_DIR,
	APPS_DIR,
	GUIAUTO_NAMESPACE_DIR,
	SCREENSHOTS_DIR,

	TESTRUN_ENVIRONMENT,
	
	SELENIUM_DRIVERS_DIR, // Place to find all drivers
	SELENIUM_DRIVER_PATH, // Overrides general look-up. If provided this absolute path is used.
	
	BROWSER_NAME,
	BROWSER_VERSION,
	BROWSER_MAXIMIZE,
	BROWSER_DIM_WIDTH,
	BROWSER_DIM_HEIGHT,
	BROWSER_BIN_PATH,
	BROWSER_DRIVER_PATH,
	BROWSER_MOBILE_PROXY_HOST,
	BROWSER_MOBILE_PROXY_ON,
	BROWSER_MOBILE_PROXY_PORT,
	BROWSER_PC_PROXY_HOST,
	BROWSER_PC_PROXY_ON,
	BROWSER_PC_PROXY_PORT,
	
	APP_URL,
	
	GUIAUTO_CONTEXT,

	GUIAUTO_SCROLL_PIXELS,
	GUIAUTO_SWIPE_TOP,
	GUIAUTO_SWIPE_BOTTOM,
	GUIAUTO_SWIPE_MAX_WAIT,
	OSTYPE,
	GUIAUTO_MAX_WAIT,
	FIREFOX_WINDOWNAME,
	CHROME_WINDOWNAME,
	SAFARI_WINDOWNAME,
	APP_PC_MAXWAIT,
	APP_MOBILE_MAXWAIT,
	APP_MOBILE_PATH,
	MOBILE_DEVICE_NAME,
	MOBILE_DEVICE_UDID,
	TEST_PC_PLATFORM,
	TEST_MOBILE_PLATFORM,
	MOBILE_PLATFORM_VERSION,
	APPIUM_HUB_URL,
	SIKULI_MAXWAIT,
	IMAGE_COMPARISON_MIN_SCORE,
	APPIUM_AUTO_LAUNCH,
}
